version: '3'

services:
    bot:
        build: ./
        restart: always
        volumes:
            - /home/soundeffect-bot/config:/var/docker/soundeffect-bot/config
            - /home/soundeffect-bot/files:/var/docker/soundeffect-bot/files